### ISSUE TITLE
Ported to Java

### ISSUE THREAD

**Issue by MitchTalmadge** [kroitor/asciichart#1]
This isn't an issue, but I wanted to let you know that I ported this library to Java. Thanks for being open source!

https://github.com/MitchTalmadge/ASCIIGraph

**Comment by kroitor** [comment]
Thanks! )

**Comment by kroitor** [comment]
@MitchTalmadge I will backlink to you from my other projects, if you don't mind )

**Comment by MitchTalmadge** [comment]
Sounds good!

**Comment by kroitor** [comment]
https://github.com/kroitor/asciichart#see-also
https://github.com/kroitor/ccxt/tree/master/examples#see-also
)

**Comment by MitchTalmadge** [comment]
That's so awesome! :D Thanks for the shout-out
