### ISSUE TITLE
Ported to Go

### ISSUE THREAD

**Issue by guptarohit** [kroitor/asciichart#13]
Hi, just wanted to tell you that I ported this awesome library to Go.
Link: [https://github.com/guptarohit/asciigraph](https://github.com/guptarohit/asciigraph)

**Comment by kroitor** [comment]
@guptarohit that's so awesome! ) Thx very much for letting me know )

**Comment by guptarohit** [comment]
@kroitor Awesome :sparkles:, thanks :+1:

**Comment by madnight** [comment]
And I just create (few mins ago) a first working version in Haskell

![](https://i.imgur.com/GMc7KRD.png)
https://github.com/madnight/asciichart

Hi kroitor : )

**Comment by kroitor** [comment]
@madnight wow! That's great news!

**Comment by kroitor** [comment]
I've added a "Ports" section, thx to you all, guys, really appreciate your involvement! )
