### ISSUE TITLE
Monospace formatting issues on web browsers

### ISSUE THREAD

**Issue by gamesguru** [kroitor/asciichart#33]
Am trying to render the raw output within <pre> tags.

<img width="1402" alt="Screen Shot 2019-10-14 at 5 37 56 PM" src="https://user-images.githubusercontent.com/30691680/66784814-8208a880-eea9-11e9-882f-9f5b791a0f03.png">

Have had this issue on Android and macOS firefox/chrome already.  My Linux computer with Chrome seems okay.

Is there anything we can do about this? Thanks.

**Comment by kroitor** [comment]
@gamesguru can you plz post the code to reproduce it?

**Comment by gamesguru** [comment]
I will try to later, but it is a browser or OS font issue not a specific glitch in the library as any graph will produce the issue on certain devices but never on others.

Chrome on linux is working
Terminal and cmd are working
macOS and android are not!!

**Comment by kroitor** [comment]
@gamesguru i'm on MacOS myself, can you plz post a complete but short snippet of code to reproduce it on my side?

**Comment by gamesguru** [comment]
I will at lunch.

are you displaying this in the terminal or safari/chrome? because the issue does not exist in terminal or iTerm, but try saving to .html and opening in chrome

**Comment by gamesguru** [comment]
@kroitor
The issue is only occurring on certain web browsers and operating systems.

Here is some such offending data.  As you will see, it renders fine on the terminal.  But when you pipe it to a `*.html` file and attempt to open it in Safari or Chrome, your troubles begin.  I am wondering if there is a quick fix for this issue?

```node
const asciichart = require('asciichart')
const fs = require('fs')

const graph = asciichart.plot([1216, 1231, 1212, 1205, 1199, 1183, 1168, 1157, 1147, 1138, 1161, 1151, 1141, 1127, 1115, 1136, 1155, 1173, 1189, 1205, 1219, 1232, 1222, 1209, 1198, 1187, 1177, 1168, 1185, 1201, 1216, 1229, 1209, 1223, 1236, 1256, 1276, 1288, 1299, 1277, 1289, 1268, 1281, 1261, 1247, 1235, 1224, 1241, 1256, 1276, 1287, 1297, 1307, 1292, 1278, 1289, 1298, 1282, 1268, 1287, 1296, 1305, 1291, 1308, 1324], { height: 10 })

console.log(graph)
fs.writeFileSync('test.html', '<pre>' + graph + '</pre>')
```

**Comment by kroitor** [comment]
> I am wondering if there is a quick fix for this issue?

Yep, just, instead of using the default font, use a true monospaced font with adequate spacing where the width of the space is equal to all other characters :

```
const asciichart = require('asciichart')
const fs = require('fs')

const graph = asciichart.plot([1216, 1231, 1212, 1205, 1199, 1183, 1168, 1157, 1147, 1138, 1161, 1151, 1141, 1127, 1115, 1136, 1155, 1173, 1189, 1205, 1219, 1232, 1222, 1209, 1198, 1187, 1177, 1168, 1185, 1201, 1216, 1229, 1209, 1223, 1236, 1256, 1276, 1288, 1299, 1277, 1289, 1268, 1281, 1261, 1247, 1235, 1224, 1241, 1256, 1276, 1287, 1297, 1307, 1292, 1278, 1289, 1298, 1282, 1268, 1287, 1296, 1305, 1291, 1308, 1324], { height: 10 })

console.log(graph)
fs.writeFileSync('test.html', '<pre style="font-family: Menlo, \'Courier New\', Courier, monospace">' + graph + '</pre>')
```

Also, if your output looks fine the terminal, but not in the browser, then compare the font that is used to render the text from your terminal settings to the default font used with your browser for pre-formatted text.

The above is not really an issue with this `asciichart` package, it's more like a routine CSS styling thing, so, if you want to know more about that, google for CSS fonts (you can also try google webfonts).

Hope that answers your question, let me know if not.

**Comment by gamesguru** [comment]
I have played around with all the so-called "monospace" fonts available through the css styling options, but nothing is working with the offended web browsers.

If there is not a lower level fix todo with the characters used (like replacing them with a more standardized monospace character *_-|/\+), then I'm afraid there isn't a fix..

**Comment by kroitor** [comment]
@gamesguru have you tried the snippet posted above with Menlo on MacOS?

> but nothing is working with the offended web browsers.

We have to be very specific, which particular browser, which particular OS, etc..

> If there is not a lower level fix todo with the characters used (like replacing them with a more standardized monospace character *_-|/+), then I'm afraid there isn't a fix..

We can add an option to change the drawing characters, but tbh I would rather do it it with CSS font styling myself, because with ascii chars `|-+` it looks more texty...

**Comment by gamesguru** [comment]
Haha, thought Menlo was a browser at first.  It does fix things in TextEdit, and _if_ I use Safari in "reader view". 
Tried the fixes [here](https://apple.stackexchange.com/questions/106083/is-there-a-way-to-set-the-default-monospace-font-in-safari) as well, no luck.

I tried your fixed script.  This is the result.  I am using `Safari 13.0.2 ` and `macOS High Sierra 10.13.6`
```
    1324.00 â”¤                                                   â•­â•®         â•­â”€ 
    1303.10 â”¤                                    â•­â”€â•®â•­â•®        â•­â”€â•¯â•°â•®â•­â”€â•® â•­â”€â”€â”€â•¯  
    1282.20 â”¤                                   â•­â•¯ â•°â•¯â•°â”€â•®     â•­â•¯   â•°â•¯ â•°â”€â•¯      
    1261.30 â”¤                                  â•­â•¯      â•°â”€â•®  â•­â•¯                
    1240.40 â”¤â•­â•®                  â•­â•®        â•­â•®â•­â”€â•¯         â•°â”€â”€â•¯                 
    1219.50 â”¼â•¯â•°â”€â•®              â•­â”€â•¯â•°â”€â•®     â•­â•¯â•°â•¯                                
    1198.60 â”¤   â•°â”€â•®           â•­â•¯    â•°â”€â•® â•­â”€â•¯                                   
    1177.70 â”¤     â•°â•®  â•­â•®     â•­â•¯       â•°â”€â•¯                                     
    1156.80 â”¤      â•°â”€â•®â”‚â•°â”€â•®  â•­â•¯                                                
    1135.90 â”¤        â•°â•¯  â•°â•®â•­â•¯                                                 
    1115.00 â”¤             â•°â•¯                                                  
```

**Comment by kroitor** [comment]
I'm on MacOS Mojave 10.14.5.

Safari Version 12.1.1 (14607.2.6.1.1):

<img width="926" alt="Screen Shot 2019-10-17 at 05 56 57" src="https://user-images.githubusercontent.com/1294454/66974183-083c0f00-f0a3-11e9-9d9e-b42b8d215a24.png">

Chrome Version 77.0.3865.90 (Official Build) (64-bit):

<img width="965" alt="Screen Shot 2019-10-17 at 05 56 51" src="https://user-images.githubusercontent.com/1294454/66974171-01ad9780-f0a3-11e9-8e53-d503555bc527.png">

> Tried the fixes here as well, no luck on plain html. But the GitHub code block I posted of the graph above is working now.

Do you have any font on your system that renders [utf-8 box drawing characters](https://en.wikipedia.org/wiki/Box-drawing_character) on your system nicely (at least one)? If not, you can try google webfonts. Also, Safari may fail to render utf-8, if your default codepage is anything else but UTF-8. What's your setting for the default encoding in Safari preferences (_advanced_ tab)?

**Comment by gamesguru** [comment]
Good call.  It was set to Latin 1.

**Comment by gamesguru** [comment]
Chrome 77.0. on Android 6.0.1 is still having the issue

**Comment by kroitor** [comment]
@gamesguru just find a font that works on most of Androids and put it before Menlo there in the code.

**Comment by gamesguru** [comment]
What's a good example of a monospace font in Android?

And do you have any info on specifying that kind of meta info? Thanks

**Comment by kroitor** [comment]
> What's a good example of a monospace font in Android?

Check out google fonts: https://github.com/googlefonts/noto-fonts/issues/617

> And do you have any info on specifying that kind of meta info?

You van do that by adding a proper and complete HTML markup with a meta charset tag set to UTF-8 in the head section: https://www.w3schools.com/tags/att_meta_charset.asp
