### ISSUE TITLE
broken chart with a big array

### ISSUE THREAD

**Issue by jjalonso** [kroitor/asciichart#36]
Im testing ascii chart with some long data array and when I console.log on terminal everything get broken, it doesnt look good

`
[ 968,
  969,
  968,
  967,
  967,
  967,
  967,
  966,
  966,
  964,
  964,
  966,
  ... 21499 more items ]
`

Basically it start printing a lot of lines, this screenshot its only a snapshot of the long print 
![Screenshot 2019-11-13 at 15 25 58](https://user-images.githubusercontent.com/389467/68777710-00cc3f00-062a-11ea-9451-77e763310f56.png)

The code im using is this. and the array result is the printed above.

```
const data = require('../data/1m/bitmex_BTCUSD_1m-15d.json');
const pricesData = data.map(tick => Math.round(tick.close));
console.log (asciichart.plot(pricesData));
```

**Comment by kroitor** [comment]
As described in the README.md for this package, the length of the chart will always be equal to the length of your data series. With the smallest fonts in the terminal you probably have 100-200 characters of width at most inside your terminal screen. Therefore you should not attempt to draw long sequences with this package. Or, you simply do `data.slice (-your_max_term_width)` before rendering to draw just the last portion of the graph that fits into your terminal window. Hope that answers the question.
