### ISSUE TITLE
Question - How to plot a live data stream

### ISSUE THREAD

**Issue by alextran1502** [kroitor/asciichart#39]
Hello,

First of all, thank you for your wonderful job. This is a very good library.

I am trying to graph a stream of data, can you help to point me in the right direction.

Thanks

**Comment by kroitor** [comment]
Hi! What's your programming language?

**Comment by alextran1502** [comment]
hello @kroitor I am using Javascript

**Comment by kroitor** [comment]
@alextran1502 assuming you can read the data points from your stream, you can add them to the set of most recent maxLength elements in your array of data upon reading, and then redraw the chart using the most recent elements. In the simplest form it would look like:

```JavaScript
const maxLength = 80
const numbers = []
while (true) {
    const number = readFromStream () // your reading logic here
    if (numbers.length >= maxLength) {
        numbers.shift ()
    }
    numbers.push (number)
    console.log (plot (numbers))
}
```

Let me know if that does not answer the question. Feel free to reopen this if needed or just ask further questions, if any.

**Comment by NightMachinary** [comment]
[**@kroitor**](https://github.com/kroitor) commented on [Feb 28, 2020, 10:13 AM GMT+3:30](https://github.com/kroitor/asciichart/issues/39#issuecomment-592344744 "2020-02-28T06:43:03Z - Replied by Github Reply Comments"):
> [@alextran1502](https://github.com/alextran1502) assuming you can read the data points from your stream, you can add them to the set of most recent maxLength elements in your array of data upon reading, and then redraw the chart using the most recent elements. In the simplest form it would look like:
> 
> ```js
> const maxLength = 80
> const numbers = []
> while (true) {
>     const number = readFromStream () // your reading logic here
>     if (numbers.length >= maxLength) {
>         numbers.shift ()
>     }
>     numbers.push (number)
>     console.log (plot (numbers))
> }
> ```
> 
> Let me know if that does not answer the question. Feel free to reopen this if needed or just ask further questions, if any.

I want to just plot the streaming data (each new line being the updated value) from stdin. How do I do that?

**Comment by kroitor** [comment]
@NightMachinary you could have the chat in a separate [blessed](https://github.com/chjj/blessed) window and redraw it when your data changes. In other words, you need to locate your chart in your output and redraw it, by overwriting it.
