### ISSUE TITLE
Need more y-axis digits

### ISSUE THREAD

**Issue by madnight** [kroitor/asciichart#5]
https://github.com/madnight/bitcoin-chart-cli/issues/9#issuecomment-350505659
> The y-axis only shows four digits of precision, so you can't see the tens of thousands.

**Comment by madnight** [comment]
Okay i found a way to get more digits by increasing the `padding: '               '`, however it might be a good idea to dynamically increase the padding so that it is possible to draw large numbers by default

**Comment by kroitor** [comment]
Hi, thx for opening this issue! It's going to be fixed here: https://github.com/kroitor/asciichart/pull/4 (merging this very soon).

**Comment by DoktorJ** [comment]
Isn't this fixed? You can use the `format` parameter now to specify how the Y axis is labeled, yes?

**Comment by kroitor** [comment]
@DoktorJ Yes, exactly. 

@madnight Closing this as solved. Feel free to reopen it if needed.
