### ISSUE TITLE
Chart not showing lines. Maybe im missing a font?

### ISSUE THREAD

**Issue by thisisloze** [kroitor/asciichart#59]
Using the CCXT basic chart example and I keep getting weird symbols.

I am running on windows.

![image](https://user-images.githubusercontent.com/22160630/107905329-9af4f400-6f0b-11eb-9863-25f7eff362f8.png)

**Comment by kroitor** [comment]
Hi @thisisloze !

> Maybe im missing a font?

Yes, you need a proper UTF-8 encoding for it. That is usually a setting of the terminal you use.
Let us know if that does not help.

**Comment by thisisloze** [comment]
Windows cmd prompt doesnt allow UTF-8 encoding.

**Comment by thisisloze** [comment]
What windows alternative can I use?

**Comment by thisisloze** [comment]
It looks like I was able to get closer usine ConsoleEMU set to UFT8 but some symbols are still unknown( but less). Any ideas?
![image](https://user-images.githubusercontent.com/22160630/107983000-50628e80-6f82-11eb-92d2-2857c0558a3e.png)

**Comment by thisisloze** [comment]
Fixed it!
For anyone using windows, you need to download ConEmu.
Setup a Startup Enviroment and add : chcp utf8
Then you need to go to fonts change the size to 20 and enable alternative font and set that to @Microsoft JhengHei Light and set UNICODE Ranges to Pseudographics!

Then it looks super nice!

**Comment by thisisloze** [comment]
Here is the end result.
![image](https://user-images.githubusercontent.com/22160630/107984018-345fec80-6f84-11eb-8dd7-8a51f6b7119d.png)
