### ISSUE TITLE
readme disagrees with license

### ISSUE THREAD

**Issue by The-Compiler** [kroitor/asciichart#60]
The README says:

> This code is absolutely free for any usage, you just do whatever the fuck you want.

Yet since 70179e1dc4bf455d6cf3dfc2e91c8209ec5f1ddc this doesn't seem to be true anymore.

**Comment by kroitor** [comment]
@The-Compiler what would you suggest?

**Comment by The-Compiler** [comment]
Given that there's a MIT license badge in the README already, perhaps that sentence should be deleted entirely?

**Comment by kroitor** [comment]
@The-Compiler does it contradict the license though?

**Comment by kroitor** [comment]
@The-Compiler i've removed it, though, tbh, OSS licensing is really confusing.

**Comment by The-Compiler** [comment]
> does it contradict the license though?

I my eyes, yes - "The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software." contradicts "do whatever the fuck you want".

> though, tbh, OSS licensing is really confusing.

I do agree!
