### ISSUE TITLE
Plotting skewed lines using / and \.

### ISSUE THREAD

**Issue by KOLANICH** [kroitor/asciichart#7]
I guess the char should be selected depending on derivative
https://github.com/mfouesneau/asciiplot/blob/master/ap.py may be useful

**Comment by kroitor** [comment]
Thank you for the proposal, I hope to add a pack of new features to this lib very soon, including the overrides for box-characters and much more. Will let you know on the progress of it. Also, your PRs and contributions are welcome!

**Comment by DoktorJ** [comment]
I agree that being able to choose the characters (or at least character "packs") is important. On my systems, based on a bare-bones Debian distro, the "pretty" curves (e.g. `╭`, `╯`) show up as unknown characters, making for a very ugly graph; in the interest of getting my script working I had to just edit the script and swap out for `┌`, `┘`, etc.

**Comment by kroitor** [comment]
@DoktorJ it's not that hard to make those symbols configurable, i'll look into adding an option for that, thx for the feedback!
